// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeYGHMwSFNRNDgqu7zNqV7RKps5bZ3clk',
    appId: '1:24096180001:web:721e13673b4495ea3e2060',
    messagingSenderId: '24096180001',
    projectId: 'meatgod-firebase',
    authDomain: 'meatgod-firebase.firebaseapp.com',
    storageBucket: 'meatgod-firebase.firebasestorage.app',
    measurementId: 'G-WQKTJSWT4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZGBRSLl7yJ5OpPCWfsRl1FB5zAfeiRk4',
    appId: '1:24096180001:android:cbac5568376e5ddb3e2060',
    messagingSenderId: '24096180001',
    projectId: 'meatgod-firebase',
    storageBucket: 'meatgod-firebase.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeYGHMwSFNRNDgqu7zNqV7RKps5bZ3clk',
    appId: '1:24096180001:web:dbc686a78bbd91bf3e2060',
    messagingSenderId: '24096180001',
    projectId: 'meatgod-firebase',
    authDomain: 'meatgod-firebase.firebaseapp.com',
    storageBucket: 'meatgod-firebase.firebasestorage.app',
    measurementId: 'G-GE4R1W0064',
  );
}
